name: 💡 Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Got an idea? We'd love to hear it!

  - type: textarea
    id: description
    attributes:
      label: What would you like?
      description: Describe the feature
      placeholder: "It would be great if..."
    validations:
      required: true

  - type: textarea
    id: why
    attributes:
      label: Why is this useful?
      description: How would this help you or others?
      placeholder: "This would allow users to..."
    validations:
      required: false

  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - Panel UI
        - Server management
        - File manager
        - Mods
        - Docker/Deployment
        - Documentation
        - Other
    validations:
      required: true
